modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "wheelchairs"
version = "2.0"
displayName = "Wheelchairs"
authors = "Lying"
description = '''
Customisable assistive devices for representation and roleplaying
'''
#logoFile = "assets/wheelchairs/icon.png"

[[dependencies.wheelchairs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wheelchairs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wheelchairs]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"